apiVersion: v1
kind: ConfigMap
metadata:
 name: task-manager-api
data:
 HTTP_PORT: "9090"
 HTTPS_PORT: "9091"
 CERT_PATH: "/etc/secret-volume/fsd_capsule_taskmanager.pfx"
 DB_TYPE: "SQLSERVER"
 DB_CONNECTION_STRING: "Server=(localdb)\\mssqllocaldb;Database=TasksDb;Trusted_Connection=True;MultipleActiveResultSets=true"
 DB_NAME: "TasksDb"
 APP_INSIGHTS_KEY: ""
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: task-manager-api
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: ingress-fsd-capsule-pp
spec:
  tls:
  - hosts: 
    - task-manager-api.fsd-capsule-pp.com
  rules:
  - host: task-manager-api.fsd-capsule-pp.com
    http:
      paths:
      - backend:
          serviceName: task-manager-api
          servicePort: 443 